### ISSUE TITLE
Sprite for bombs

### ISSUE THREAD

**Issue by funwillis** [gamedev-mallorca/bomberman#2]
Create [sprite](https://en.wikipedia.org/wiki/Sprite_(computer_graphics)) for bombs spawned by #1

**Comment by gonz4lex** [comment]
Hello,

I would also be able to take on this issue, please let me know your thoughts. :)

Thank you,
Alex

**Comment by gonz4lex** [comment]
Hello again,

I have uploaded a first version of the bomb sprite to [Drive](https://drive.google.com/drive/folders/1tINj4urIji16-KgDvgoOQfT2QFodG26o). The image is 32x32 pixels and the animation is 5 frames long.

Here is a preview:

![Bomb Sprite](https://user-images.githubusercontent.com/37397988/68885283-22eebb80-0715-11ea-9a4c-b6d2cab15add.gif)

Please feel free to check it out and let me know any comments you might have.
Thanks!
